### ISSUE TITLE
Verify webhook signature

### ISSUE THREAD

**Issue by QuLogic** [SciTools-incubator/scitools-cla-checker#11]
As evidenced in #10, I can send arbitrary triggers to the webhook without authentication or verification. GitHub apparently sends an [`X-Hub-Signature` header](https://developer.github.com/webhooks/#delivery-headers) using a secret which could possibly be used to verify the webhook sender and payload.

**Comment by pelson** [comment]
Agreed. I decided not to check this because the behaviour is a tightly limited set, but there is no harm in preventing arbitrary execution of that set.

Thanks @QuLogic

**Comment by pelson** [comment]
Closed in #12. Thanks @QuLogic.
